services:

  med_back:
    container_name: med_back
    build: .
    ports:
      - 8088:8088
    environment:
      MED_DB_HOST: ${MED_DB_HOST}
      MED_DB_PORT: ${MED_DB_PORT}
      MED_DB_USER: ${MED_DB_USER}
      MED_DB_NAME: ${MED_DB_NAME}
      MED_DB_PASSWORD: ${MED_DB_PASSWORD}
      ACCESS_TOKEN_KEY: dsjkaiortenfbsu423djlkfut4965j2klfu854
      REFRESH_TOKEN_KEY: 4328kfdljskf34857349iofjkdhsjfu84359fjklg8435
      ACCESS_EXPIRE_TIME_LIFE: 10
      REFRESH_EXPIRE_TIME_LIFE: 30
      ALGORITHM: HS256
      REDIS_URL: redis://med_rd:6379
    networks:
      - med
    restart: unless-stopped
    tty: true
    stdin_open: true

  med_db:
    container_name: med_db
    image: postgres:18-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${MED_DB_USER}
      POSTGRES_PASSWORD: ${MED_DB_PASSWORD}
      POSTGRES_DB: ${MED_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d med_pro"]
      interval: 20s
      timeout: 10s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - med
    
  med_rd:
    container_name: med_rd
    image: redis:8.4-alpine
    restart: always
    ports:
      - 6380:6379
    volumes:
      - ./cache:/data
    networks:
      - med

networks:
  med:
    driver: bridge
